language: php

php:
  - 5.6
  - 7.0
  - 7.1

before_script:
    - curl -s http://getcomposer.org/installer | php
    - COMPOSER_ROOT_VERSION=dev-master php -d memory_limit=-1 composer.phar install --dev
